// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employee struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Salary int    `json:"salary"`
}

func (Employee) IsEntity() {}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
