package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"todo-server/graph/generated"
	"todo-server/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, employeeID string, content string) (*model.Todo, error) {
	todo := &model.Todo{
		ID:         r.nextTodoID(),
		EmployeeID: employeeID,
		Content:    content,
		UpdatedAt:  nowRFC3339(),
		Deleted:    false,
	}

	r.mu.Lock()
	r.todos[todo.ID] = todo
	r.upsertEmployeeIndexNoLock(employeeID, todo.ID)
	r.mu.Unlock()

	if err := r.publishTodoEvent(ctx, "created", todo); err != nil {
		r.mu.Lock()
		delete(r.todos, todo.ID)
		r.removeEmployeeIndexNoLock(employeeID, todo.ID)
		r.mu.Unlock()
		return nil, fmt.Errorf("publish created event: %w", err)
	}

	return cloneTodo(todo), nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, content string) (*model.Todo, error) {
	r.mu.Lock()
	todo, ok := r.todos[id]
	if !ok || todo.Deleted {
		r.mu.Unlock()
		return nil, fmt.Errorf("todo %q not found", id)
	}

	original := cloneTodo(todo)
	todo.Content = content
	todo.UpdatedAt = nowRFC3339()
	updated := cloneTodo(todo)
	r.mu.Unlock()

	if err := r.publishTodoEvent(ctx, "updated", updated); err != nil {
		r.mu.Lock()
		if current, exists := r.todos[id]; exists {
			current.Content = original.Content
			current.UpdatedAt = original.UpdatedAt
			current.Deleted = original.Deleted
		}
		r.mu.Unlock()
		return nil, fmt.Errorf("publish updated event: %w", err)
	}

	return updated, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (*model.Todo, error) {
	r.mu.Lock()
	todo, ok := r.todos[id]
	if !ok || todo.Deleted {
		r.mu.Unlock()
		return nil, fmt.Errorf("todo %q not found", id)
	}

	original := cloneTodo(todo)
	todo.Deleted = true
	todo.UpdatedAt = nowRFC3339()
	deletedTodo := cloneTodo(todo)
	r.removeEmployeeIndexNoLock(todo.EmployeeID, todo.ID)
	r.mu.Unlock()

	if err := r.publishTodoEvent(ctx, "deleted", deletedTodo); err != nil {
		r.mu.Lock()
		if current, exists := r.todos[id]; exists {
			current.Deleted = original.Deleted
			current.UpdatedAt = original.UpdatedAt
			r.upsertEmployeeIndexNoLock(current.EmployeeID, current.ID)
		}
		r.mu.Unlock()
		return nil, fmt.Errorf("publish deleted event: %w", err)
	}

	return deletedTodo, nil
}

// EmployeeTodos is the resolver for the employeeTodos field.
func (r *queryResolver) EmployeeTodos(ctx context.Context, employeeID string) ([]*model.Todo, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.listTodosByEmployeeNoLock(employeeID), nil
}

// TodoByID is the resolver for the todoByID field.
func (r *queryResolver) TodoByID(ctx context.Context, id string) (*model.Todo, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	todo, ok := r.todos[id]
	if !ok || todo.Deleted {
		return nil, nil
	}
	return cloneTodo(todo), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
