package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"demo-opa-graphql/graph/generated"
	"demo-opa-graphql/graph/model"
	"demo-opa-graphql/internal/security"
	"errors"
	"fmt"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string) (*model.Post, error) {
	if err := r.authorize(ctx, "mutation", "createPost", map[string]interface{}{"title": title}); err != nil {
		return nil, err
	}

	principal, ok := security.PrincipalFromContext(ctx)
	if !ok {
		return nil, errUnauthenticated
	}

	return &model.Post{
		ID:       r.nextPostID(),
		Title:    title,
		AuthorID: principal.Subject,
	}, nil
}

// PublicInfo is the resolver for the publicInfo field.
func (r *queryResolver) PublicInfo(ctx context.Context) (string, error) {
	if err := r.authorize(ctx, "query", "publicInfo", nil); err != nil {
		return "", err
	}
	return "public graphql endpoint is healthy", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	if err := r.authorize(ctx, "query", "me", nil); err != nil {
		if errors.Is(err, errUnauthenticated) {
			return nil, fmt.Errorf("unauthenticated: provide bearer token")
		}
		return nil, err
	}

	principal, ok := security.PrincipalFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated: principal missing")
	}

	record := r.lookupUser(principal.Subject, principal.Roles)
	return &model.User{
		ID:    record.ID,
		Name:  record.Name,
		Roles: append([]string(nil), record.Roles...),
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
