// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employee struct {
	ID    string  `json:"id"`
	Todos []*Todo `json:"todos"`
}

func (Employee) IsEntity() {}

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID         string `json:"id"`
	EmployeeID string `json:"employeeID"`
	Content    string `json:"content"`
	UpdatedAt  string `json:"updatedAt"`
	Deleted    bool   `json:"deleted"`
}

func (Todo) IsEntity() {}
