package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"graphql-server/graph/generated"
	"graphql-server/graph/model"
)

var employees = []*model.Employee{
	{ID: "emp-1", Name: "Alice", Salary: 50000},
	{ID: "emp-2", Name: "Bob", Salary: 60000},
	{ID: "emp-3", Name: "Charlie", Salary: 70000},
}

// EmployeeByID is the resolver for the employeeByID field.
func (r *queryResolver) EmployeeByID(ctx context.Context, id string) (*model.Employee, error) {
	for _, emp := range employees {
		if emp.ID == id {
			return emp, nil
		}
	}
	return nil, nil
}

// Employees is the resolver for the employees field.
func (r *queryResolver) Employees(ctx context.Context) ([]*model.Employee, error) {
	return employees, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
